### PR TITLE
fix monthly spent bug in analyticsModelManager

### LINKED ISSUE #132: Get monthly spent function applies to all dates with the same month
In the AnalyticModelManager, the getMonthlySpent function wrongly checks for the current month as a value and sums the expenses which have the same month. This is incorrect behavior, since expenses under the same month but in a different year would also be counted.

### PR DESCRIPTION
**Pull request by nicleejy**
Closes #132

### CODE REVIEW

File: src/main/java/seedu/address/model/AnalyticModelManager.java [hunk 1]
```diff
@@ -80,16 +80,21 @@ public AnalyticModelManager(ReadOnlyExpenseTracker expenseTracker) {
...
         double total = 0;
+        int currentYear = currentDate.getYear();
         int currentMonth = currentDate.getMonthValue();
+        LocalDate startOfMonth = LocalDate.of(currentYear, currentMonth, 1);
+        LocalDate endOfMonth = startOfMonth.with(TemporalAdjusters.lastDayOfMonth());
         for (Expense expense: allExpenses) {
-            if (expense.getDate().getMonthValue() == currentMonth) {
+            LocalDate expenseDate = expense.getDate();
+            if (expenseDate.isAfter(startOfMonth) && expenseDate.isBefore(endOfMonth)) {
                 total += expense.getAmount();
```
Comment (shirsho-12) [inline src/main/java/seedu/address/model/AnalyticModelManager.java:90]: Looks like the bug has been fixed.

**Review by shirsho-12 — APPROVED** [review]
LGTM
