### PR TITLE
Fix find and edit expense combined bug.

### LINKED ISSUE #160: [PE-D][Tester B] Find list does not update after edit
I did `find fare` and proceed to edit the word fare out of the name. A quick fix might be to simply show every item in the list after each edit.

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: ShawnYip-Au/ped#3

### PR DESCRIPTION
**Pull request by gitsac**
Closes #160

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/EditExpenseCommand.java [hunk 1]
```diff
@@ -112,7 +112,7 @@ public CommandResult execute(Model model) throws CommandException {
         }
 
         Expense newExpense = new Expense(name, amount, date, category);
-        model.setExpense(targetIndex.getZeroBased(), newExpense);
+        model.setExpense(expenseToEdit, newExpense);
```
Comment (shirsho-12) [inline src/main/java/seedu/address/logic/commands/EditExpenseCommand.java:115]: good catch

File: src/main/java/seedu/address/model/ModelManager.java [hunk 2]
```diff
@@ -212,7 +212,7 @@ public ObservableList<Expense> getFilteredExpenseList() {
      */
     @Override
     public void setExpense(Expense target, Expense editedExpense) {
-        //TODO implement this method for editing an expense
+        expenseTracker.setExpense(target, editedExpense);
     }
```
Comment (shirsho-12) [inline src/main/java/seedu/address/model/ModelManager.java:216]: good job

**Review by shirsho-12 — APPROVED** [review]
