### PR TITLE
Bug Fixes Round 1

### LINKED ISSUE #175: [PE-D][Tester A] Price can be negative
The price of an expense can be negative.

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: NBQian/ped#6

### LINKED ISSUE #177: [PE-D][Tester C] `addcat` recognises `Housing` and `housing` as the same category, however `edexp` does not
Steps to reproduce:
1. Launch with default data
2. `addcat c/housing`: shows error message `This category already exists in FastTrack`
3. `edexp 2 c/housing`

    Expected: edits expense successfully;

    Actual: shows error message `The provided category does not exist!`;

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: chia-yh/ped#5

### PR DESCRIPTION
**Pull request by shirsho-12**
Closes #177 
Closes #175

### CODE REVIEW

**Comment by shirsho-12** [comment]
closes #167 
closes #170 
closes #179

File: src/main/java/seedu/address/model/expense/Expense.java [hunk 1]
```diff
@@ -30,19 +30,47 @@ public class Expense {
      * @param date     Date of the expense
      * @param category Category of the expense
      */
-    public Expense(String name, double amount, LocalDate date, Category category) {
+    public Expense(String name, Price amount, LocalDate date, Category category) {
```
Comment (gitsac) [inline src/main/java/seedu/address/model/expense/Expense.java:33]: Good to refactor to use Price class instead of the previous double.

File: src/main/java/seedu/address/model/expense/ExpenseList.java [hunk 2]
```diff
@@ -140,7 +140,7 @@ public boolean equals(Object other) {
      */
     public boolean contains(Expense toCheck) {
         requireNonNull(toCheck);
-        return internalListOfExpenses.stream().anyMatch(toCheck::isSameExpense);
+        return internalListOfExpenses.stream().anyMatch(toCheck::equals);
```
Comment (gitsac) [inline src/main/java/seedu/address/model/expense/ExpenseList.java:143]: Good to declutter the codebase for expenses by using overriding equals method instead of defining extra methods.

**Review by gitsac — APPROVED** [review]
Good refactoring to declutter current codebase. LGTM.
