### PR TITLE
Change app name, fix recurring expense bug, fix save on exit bug

### LINKED ISSUE #154: [PE-D][Tester A] Wrong app name
The name of the app is still "Address App" instead of FastTrack.

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: NBQian/ped#1

### LINKED ISSUE #171: [PE-D][Tester E] Bug: Quitting the application with CMD+Q did not save the list
After quitting the application with CMD+Q and reopening the program, the list did not initialise with the previous list nor a test list but was instead empty.

Not sure why this behaviour happened as the very first startup of the program created a test list containing entries already, however it seems to have completely wiped that record.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: joshua-tyh/ped#4

### LINKED ISSUE #174: [PE-D][Tester B] Add command somehow added multiple duplicates of the same items.
It's definitely not feasible for me to do this 2406 times. Apologies that I do not know how to replicate this, I only this found out as I was playing around with find. It could be due to the bug where if the date year is 00, the programs hangs for a bit as that was the command that added 'milk'. All the best.

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: ShawnYip-Au/ped#8

### LINKED ISSUE #188: [PE-D][Tester C] Window title is `Address App` instead of `FastTrack` or relevant title
_This issue is purely cosmetic_

Steps to reproduce:
1. launch FastTrack

Window title is `Address App`, could be confusing to users as the application has nothing to do with addresses, and is concerned mainly with tracking expenses.

-------------
Labels: `type.FeatureFlaw` `severity.VeryLow`
original: chia-yh/ped#8

### LINKED ISSUE #189: [PE-D][Tester D] Feature Bug - Application Title not updated
Application Name not updated, again a very manageable bug to handle. Do update it accordingly. Currently it is named "address app" still.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: daniellingzy/ped#4

### PR DESCRIPTION
**Pull request by nicleejy**
Closes #171
Closes #189 
Closes #188 
Closes #174 
Closes #154

### CODE REVIEW

File: src/main/java/seedu/address/model/expense/RecurringExpenseManager.java [hunk 1]
```diff
@@ -100,7 +100,11 @@ public RecurringExpenseManager(String expenseName, double amount,
 
     public ArrayList<Expense> getExpenses() {
         ArrayList<Expense> expenses = new ArrayList<>();
-        while (nextExpenseDate.isBefore(LocalDate.now())) {
+        LocalDate newEndDate = LocalDate.now();
+        if (endDate != null) {
+            newEndDate = !endDate.isAfter(LocalDate.now()) ? endDate : LocalDate.now();
+        }
+        while (!nextExpenseDate.isAfter(newEndDate)) {
```
Comment (shirsho-12) [inline src/main/java/seedu/address/model/expense/RecurringExpenseManager.java:107]: important bug fix

**Review by shirsho-12 — APPROVED** [review]
