### PR TITLE
Bug fixes for UI, autocomplete

### LINKED ISSUE #158: [PE-D][Tester C] Help Window too large, can't close it directly or resize to reach close button
Steps to reproduce:
1. type `help` or click "Help" in menu bar

Help window that pops up is way too large (pictured above, spans beyond the height of the screen), can't access the close button to continue using the app. Have to either exit the app or close through alt-tab.

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: chia-yh/ped#1

### LINKED ISSUE #185: [PE-D][Tester B] Misalignment
-------------
Labels: `severity.VeryLow` `type.FeatureFlaw`
original: ShawnYip-Au/ped#11

### LINKED ISSUE #192: [PE-D][Tester A] Auto completion of category name does not match the suggested category
The suggested category is "Groceries" but when "ENTER" is pressed to use auto-completion, the word "groceries" is filled instead

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: NBQian/ped#8

### PR DESCRIPTION
**Pull request by nicleejy**
closes #192 
closes #185 
closes #158

### CODE REVIEW

File: src/main/java/fasttrack/ui/CommandBox.java [hunk 1]
```diff
@@ -115,6 +115,9 @@ private void initialiseAutocompleteHandler() {
             if (event.getCode() == KeyCode.UP && suggestionsList.isVisible()) {
                 suggestionsList.requestFocus();
             }
+            if (event.getCode() == KeyCode.ENTER && suggestionsList.isVisible()) {
+                suggestionsList.setVisible(false);
+            }
```
Comment (shirsho-12) [inline src/main/java/fasttrack/ui/CommandBox.java:120]: Good fix

File: src/main/java/fasttrack/ui/UiManager.java [hunk 2]
```diff
@@ -42,6 +42,10 @@ public void start(Stage primaryStage) {
             mainWindow = new MainWindow(primaryStage, logic);
             mainWindow.show(); //This should be called before creating other UI parts
             mainWindow.fillInnerParts();
+            primaryStage.sizeToScene();
+            primaryStage.setHeight(700);
+            primaryStage.setMinWidth(1000);
+            primaryStage.setMinHeight(700);
```
Comment (shirsho-12) [inline src/main/java/fasttrack/ui/UiManager.java:48]: Ah the minimum and maximum size complaints

**Review by shirsho-12 — APPROVED** [review]
